name: my workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "HEllo world"
        shell: bash

  good-bye:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: bye bye
        run: echo "bye bye"
        shell: bash
  